name: Build Mod
  on: push

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'

        - name: Build with Gradle
          # We are skipping the 'setup-gradle' action entirely
          # because its cache is what is crashing GitHub's servers.
          run: gradle build

        - name: Upload Mod Jar
          uses: actions/upload-artifact@v4
          with:
            name: SaturationBarMod
            path: build/libs/*.jar
