name: Build Mod
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        # --no-daemon prevents the server from getting confused by background processes
        # -Dorg.gradle.jvmargs="-Xmx2G" gives the build more memory
        run: gradle build --no-daemon -Dorg.gradle.jvmargs="-Xmx2G"

      - name: Upload Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: SaturationBarMod
          path: build/libs/*.jar
